In [ ]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import plotly.express as px
import numpy as np
from sklearn import preprocessing
from sklearn.model_selection import train_test_split
import random
import sklearn.linear_model as sklm
from sklearn import metrics
from sklearn.linear_model import Ridge, RidgeCV, Lasso, LassoCV, LinearRegression
import math

In [ ]:
file_path = '/content/drive/MyDrive/identify_fake_generated_image/train.csv'
df = pd.read_csv(file_path)
df.head(11)

labels       f_0       f_1       f_2       f_3       f_4       f_5  \
0        0 -2.033875  0.978446 -0.142131 -0.177117 -1.470684  1.669562   
1        1 -0.348835  0.294815 -0.557577 -2.020773 -1.234715  1.633930   
2        1  0.113248 -0.607726 -0.947791  0.830851  0.998291  0.498321   
3        0  1.223321 -0.479048 -1.925789  1.680377  0.021840 -1.453307   
4        0  0.160109  0.422684 -0.308029  0.227744  0.432854  0.608348   
5        0 -0.526642 -0.590432  0.328210 -0.547433 -0.692556  0.175954   
6        0 -0.199279  0.831787 -1.052687  0.491722 -0.571469 -1.449519   
7        0 -0.906233  0.987997 -2.056229  1.078932  0.501608  0.826041   
8        0 -0.283658  0.964051 -0.349123 -0.162445  0.238172  0.501472   
9        0  1.382773 -2.415394  0.969006 -1.690371  1.509442  0.914959   
10       1 -0.932571  1.366246  0.364603  2.126203  0.705695  0.066673   

         f_6       f_7       f_8  ...    f_1190    f_1191    f_1192    f_1193  \
0  -0.196530 -0.125239 -0.452284  ... -1.111266  0.716084  0.060039  0.301279   
1  -1.680658 -0.358146  0.166122  ...  0.735240  0.829781  1.521941  1.347946   
2  -1.493958  0.789572 -1.311018  ...  0.104698  0.616189 -1.035953  2.111387   
3   0.605559 -0.019024  1.065448  ...  0.360237 -1.957863 -0.123384  1.505329   
4   0.193832  1.035091 -0.538868  ...  0.416629  1.441766  0.212572 -0.994721   
5   0.539330  0.578212  0.547327  ...  1.131889  0.250693 -0.215257  0.236730   
6  -0.227167  0.451431  0.090848  ...  1.081787  0.875338 -1.217201 -0.297249   
7  -0.136533 -0.931548 -0.657145  ...  1.041859 -0.313667  1.492701 -0.425727   
8   0.413006 -1.183602 -0.221886  ... -1.612677 -0.714356 -0.033445 -2.350722   
9  -0.161389  0.952598 -0.044989  ...  0.875176 -0.855081  0.318588  0.252447   
10 -0.796001 -1.204584 -0.579558  ...  0.403565 -0.092736 -0.051202  1.109147   

      f_1194    f_1195    f_1196    f_1197    f_1198    f_1199  
0  -1.174846 -1.076498 -0.069452 -0.604012 -2.179176  0.558003  
1   0.754505  1.330642 -0.754453  0.582956  0.252671  1.495870  
2  -0.984415  1.148076 -1.433554  0.243372  0.170083  1.274795  
3   0.660290 -1.769443 -0.547756 -0.568122  0.244645  0.982116  
4   1.143999 -2.166923 -1.199248 -1.028636  0.752791  0.317169  
5   0.905414 -0.102015 -2.453250 -1.562715 -0.324501  1.590111  
6  -0.133911 -0.865070 -0.128914  1.153154  0.363864  0.670339  
7  -0.425587 -0.408214  2.041689  0.814182  0.211569  0.343013  
8  -1.373337 -1.521727  0.015327  0.114279  1.320421  0.979955  
9   0.400645  1.732217 -0.390191  0.628386 -1.518295 -0.218986  
10  0.028089 -0.467010 -0.072701  0.181085  1.065936 -1.294234  

[11 rows x 1201 columns]

In [ ]:
df_labels_fake = df[df.labels==0]
df_labels_real = df[df.labels==1]

In [ ]:
df_labels_fake.describe()

In [ ]:
df_labels_fake.head(10)

In [ ]:
df_labels_real.describe()

In [ ]:
df_labels_real.head(10)

In [ ]:
df.describe()

In [ ]:
X = df.drop(['labels'],axis=1)
y = df['labels']
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=2)

In [ ]:
X_try = df.iloc[:,1:1201]
y_try = df.iloc[:,0]

In [ ]:
X_try.shape

(5250, 1200)

In [ ]:
y_try

tensor([[0.],
        [1.],
        [1.],
        ...,
        [1.],
        [1.],
        [1.]])

In [ ]:
X_train_try, X_test_try, y_train_try, y_test_try = train_test_split(X_try, y_try, train_size=0.7, shuffle=True)

In [ ]:
y_try.shape

torch.Size([5250, 1])

In [ ]:
import torch
X_try = torch.tensor(X_try.values, dtype=torch.float32)
y_try = torch.tensor(y_try, dtype=torch.float32).reshape(-1, 1)

In [ ]:
X

In [ ]:
X_train

In [ ]:
X_test

In [ ]:
y

### Training using Logistic Regression

In [ ]:
model_LG = LinearRegression()
model_LG.fit(X_train, y_train)
y_predlinear = model_LG.predict(X_test)
# print(y_predlinear)
y_predlinear_new = []
for target in y_predlinear:
  y_predlinear_new.append(round(target))
# print(y_predlinear_new)
# y_predlinear = round(y_predlinear)
print("Accuracy:", metrics.accuracy_score(y_test, y_predlinear_new))

Accuracy: 0.7628571428571429


### Training using Ridge Regression

In [ ]:
model_ridge = Ridge(alpha=0.01)
model_ridge.fit(X_train, y_train)
y_predridge = model_ridge.predict(X_test)
y_predridge_new = []
for target in y_predridge:
  y_predridge_new.append(round(target))
# print(y_predlinear_new)
# y_predlinear = round(y_predlinear)
print("Accuracy:", metrics.accuracy_score(y_test, y_predridge_new))

Accuracy: 0.7628571428571429


### Training using XGB Regressor

In [ ]:
import xgboost
from xgboost import XGBRegressor
model_xgbr = XGBRegressor(objective ='reg:squarederror', n_estimators = 10, seed = 0, max_depth = 3)
model_xgbr.fit(X_train, y_train)
y_predxgbr = model_xgbr.predict(X_test)
y_predxgbr_new = []
for target in y_predxgbr:
  y_predxgbr_new.append(round(target))
# print(y_predlinear_new)
# y_predlinear = round(y_predlinear)
print("Accuracy:", metrics.accuracy_score(y_test, y_predxgbr_new))

Accuracy: 0.8314285714285714


### Training using Gradient Boosting

In [ ]:
from sklearn.ensemble import GradientBoostingClassifier
clf = GradientBoostingClassifier(n_estimators=100, learning_rate=0.1,
    max_depth=3, random_state=20)
clf.fit(X_train, y_train)
y_predgboost = clf.predict(X_test)
y_predgboost_new = []
for target in y_predgboost:
  y_predgboost_new.append(round(target))
print("Accuracy:", metrics.accuracy_score(y_test, y_predgboost_new))

Accuracy: 0.8542857142857143


### Training using Deep Neural Network
Here i want to do binary classification which is the output only give me one class (0 or 1).
But i am interested what happen if i want the model give me two class but with probability of each class, and then i will select the bigger probability

In [ ]:
from torch.utils.data import Dataset, DataLoader, TensorDataset
import torch
import torch.optim as optim
import torch.nn as nn
import torch.nn.functional as F
from torchvision import models
from datetime import datetime

In [ ]:
fix_X = np.float32(X_train)
fix_y = np.float32(y_train)
fix_X_train = torch.from_numpy(fix_X)
fix_y_train = torch.from_numpy(fix_y)
# dataset = TensorDataset(fix_X_train, fix_y_train)
# data_loader = DataLoader(dataset, batch_size = 16, shuffle = True)

In [ ]:
fix_X_train.shape

torch.Size([4200, 1200])

In [ ]:
fix_y_train.shape
fix_y_train

tensor([0., 0., 0.,  ..., 0., 0., 1.])

In [ ]:
fix_y_train.long()

tensor([0, 0, 0,  ..., 0, 0, 1])

In [ ]:
fix_X.shape

(4200, 1200)

In [ ]:
X_train_try.shape

torch.Size([3674, 1200])

In [ ]:
y_train_try.shape

torch.Size([3674, 1])

In [ ]:
class Wide(nn.Module):
    def __init__(self):
        super().__init__()
        self.hidden = nn.Linear(1200, 2400)
        self.relu = nn.ReLU()
        self.output = nn.Linear(2400, 1)
        self.sigmoid = nn.Sigmoid()
 
    def forward(self, x):
        x = self.relu(self.hidden(x))
        x = self.sigmoid(self.output(x))
        return x

In [ ]:
class Deep(nn.Module):
    def __init__(self):
        super().__init__()
        self.layer1 = nn.Linear(1200, 800)
        self.act1 = nn.ReLU()
        self.layer2 = nn.Linear(800, 800)
        self.act2 = nn.ReLU()
        self.layer3 = nn.Linear(800, 800)
        self.act3 = nn.ReLU()
        self.output = nn.Linear(800, 1)
        self.sigmoid = nn.Sigmoid()
 
    def forward(self, x):
        x = self.act1(self.layer1(x))
        x = self.act2(self.layer2(x))
        x = self.act3(self.layer3(x))
        x = self.sigmoid(self.output(x))
        return x

In [ ]:
# Define artificial neural network model (1 class output)
model_ann_bc = nn.Sequential(
    nn.Linear(1200,3600),
    nn.ReLU(),
    nn.Linear(3600,3600),
    nn.ReLU(),
    nn.Linear(3600,1),
    nn.Sigmoid()
)
# model.cuda()
opt_bc = optim.Adam(
    model_ann_bc.parameters(),
    lr=1e-3,
    weight_decay=1e-5
)
loss_fn_bc = nn.BCELoss()

In [ ]:
# Define artificial neural network model (2 class output)
model_ann_mc = nn.Sequential(
    nn.Linear(1200,100),
    nn.ReLU(),
    nn.Linear(100,100),
    nn.ReLU(),
    nn.Linear(100,2)
)
# model.cuda()
opt_mc = optim.Adam(
    model_ann_mc.parameters(),
    lr=1e-3,
    weight_decay=1e-5
)
loss_fn_mc = nn.CrossEntropyLoss()

In [ ]:
# Define deep neural network model (1 class output)
model_dnn_bc = nn.Sequential(
    nn.Linear(1200,1200),
    nn.ReLU(),
    nn.Linear(1200,1200),
    nn.ReLU(),
    nn.Linear(1200,1200),
    nn.ReLU(),
    nn.Linear(1200,1),
    nn.Sigmoid()
)
# model.cuda()
opt_dnn_bc = optim.Adam(
    model_dnn_bc.parameters(),
    lr=1e-3,
    weight_decay=1e-5
)
loss_fn_dnn_bc = nn.BCELoss()

In [ ]:
# Define deep neural network model (2 class output)
model_dnn_mc = nn.Sequential(
    nn.Linear(1200,500),
    nn.ReLU(),
    nn.Linear(500,300),
    nn.ReLU(),
    nn.Linear(300,100),
    nn.ReLU(),
    nn.Linear(100,70),
    nn.ReLU(),
    nn.Linear(70,50),
    nn.ReLU(),
    nn.Linear(50,30),
    nn.ReLU(),
    nn.Linear(30,10),
    nn.ReLU(),
    nn.Linear(10,2)
)
# model.cuda()
opt_dnn_mc = optim.Adam(
    model_dnn_mc.parameters(),
    lr=1e-3,
    weight_decay=1e-5
)
loss_fn_dnn_mc = nn.CrossEntropyLoss()

In [ ]:
# Training time for ann binary classification
model_ann_bc = Wide()
loss_fn_ann_bc = nn.BCELoss()  # binary cross entropy
opt_ann_bc = optim.Adam(model_ann_bc.parameters(), lr=0.0001)
for t in range(50):
    model_ann_bc.train()
    # Feed forward to get the logits
    y_pred_ann_bc = model_ann_bc(X_train_try)
    # print(y_pred_ann)
    # print(fix_y_train.long())
    
    # Compute the loss and accuracy
    loss_ann_bc = loss_fn_bc(y_pred_ann_bc, y_train_try)
    acc_ann_bc = (y_train_try == y_pred_ann_bc.round()).float().mean()
    print('[EPOCH]: %i, [LOSS]: %.6f, [ACCURACY]: %.3f' % (t, loss_ann_bc, acc_ann_bc))
    # Zero the gradients before warning the backward pass
    opt_bc.zero_grad()
    
    # Backward pass
    loss_ann_bc.backward()
    
    # Update parameters
    opt_bc.step()

In [ ]:
# Training time for ann multiclass classification
for t in range(50):
    # Feed forward to get the logits
    y_pred_ann_mc = model_ann_mc(fix_X_train)
    # print(y_pred_ann)
    # print(fix_y_train.long())
    
    # Compute the loss and accuracy
    loss_ann_mc = loss_fn_mc(y_pred_ann_mc, fix_y_train.long())
    score_ann_mc, predicted_ann_mc = torch.max(y_pred_ann_mc, 1)
    acc_ann_mc = (fix_y_train == predicted_ann_mc).sum().float() / len(fix_y_train)
    print('[EPOCH]: %i, [LOSS]: %.6f, [ACCURACY]: %.3f' % (t, loss_ann_mc, acc_ann_mc))
    
    # Zero the gradients before warning the backward pass
    opt_mc.zero_grad()
    
    # Backward pass
    loss_ann_mc.backward()
    
    # Update parameters
    opt_mc.step()

In [ ]:
# Training time for dnn binary classification
model_dnn_bc = Deep()
loss_fn_dnn_bc = nn.BCELoss()  # binary cross entropy
opt_dnn_bc = optim.Adam(model_dnn_bc.parameters(), lr=0.0001)
for t in range(100):
    # Feed forward to get the logits
    y_pred_dnn_bc = model_dnn_bc(X_train_try)
    # print(y_pred_dnn)
    # print(fix_y_train.long())
    
    # Compute the loss and accuracy
    loss_dnn_bc = loss_fn_dnn_bc(y_pred_dnn_bc, y_train_try)
    
    # Zero the gradients before warning the backward pass
    opt_dnn_bc.zero_grad()
    
    # Backward pass
    loss_dnn_bc.backward()
    
    # Update parameters
    opt_dnn_bc.step()

    acc_dnn_bc = (y_train_try == y_pred_dnn_bc.round()).float().mean()
    print('[EPOCH]: %i, [LOSS]: %.6f, [ACCURACY]: %.3f' % (t, loss_dnn_bc, acc_dnn_bc))

In [ ]:
# Training time for dnn multiclass classification
for t in range(50):
    # Feed forward to get the logits
    y_pred_dnn_mc = model_dnn_mc(fix_X_train)
    # print(y_pred_dnn)
    # print(fix_y_train.long())
    
    # Compute the loss and accuracy
    loss_dnn_mc = loss_fn_dnn_mc(y_pred_dnn_mc, fix_y_train.long())
    score_dnn_mc, predicted_dnn_mc = torch.max(y_pred_dnn_mc, 1)
    acc_dnn_mc = (fix_y_train == predicted_dnn_mc).sum().float() / len(fix_y_train)
    print('[EPOCH]: %i, [LOSS]: %.6f, [ACCURACY]: %.3f' % (t, loss_dnn_mc, acc_dnn_mc))
    
    # Zero the gradients before warning the backward pass
    opt_dnn_mc.zero_grad()
    
    # Backward pass
    loss_dnn_mc.backward()
    
    # Update parameters
    opt_dnn_mc.step()

In [ ]:
PATH = '/content/modelnn.pth'
torch.save(model.state_dict(), PATH)

In [ ]:
# test with validation set using ann model
fix_X_val = np.float32(X_test)
# fix_y_val = np.float32(y_test)
fix_X_valid = torch.from_numpy(fix_X_val)
# fix_y_valid = torch.from_numpy(fix_y_val)
y_pred_val_ann = model_ann(fix_X_valid)
# y_pred_val.shape
# y_pred_val
score,predicted = torch.max(y_pred_val_ann,1)
predicted_array_ann = predicted.numpy()
print("Accuracy:", metrics.accuracy_score(y_test, predicted_array_ann))

Accuracy: 0.8180952380952381


In [ ]:
y_pred_val_dnn_bc = model_dnn_bc(X_test_try)
y_pred_val_dnn_bc_new = y_pred_val_dnn_bc.round()
print(y_pred_val_dnn_bc_new)
predicted_array_dnn_bc = y_pred_val_dnn_bc_new.detach().numpy()
print("Accuracy:", metrics.accuracy_score(y_test_try, predicted_array_dnn_bc))

tensor([[1.],
        [0.],
        [1.],
        ...,
        [0.],
        [0.],
        [0.]], grad_fn=<RoundBackward0>)
Accuracy: 0.8426395939086294


In [ ]:
tensor.detach().numpy()

In [ ]:
predicted_array_ann

array([0, 0, 1, ..., 1, 0, 1])

In [ ]:
y_test

622     0
4709    0
1471    0
4030    0
4100    1
       ..
1614    0
1239    0
5234    1
1298    0
5204    1
Name: labels, Length: 1050, dtype: int64

In [ ]:
# test with validation set using dnn model
y_pred_val_dnn = model_dnn(fix_X_valid)
score_dnn,predicted_dnn = torch.max(y_pred_val_dnn,1)
predicted_array_dnn = predicted_dnn.numpy()
print("Accuracy:", metrics.accuracy_score(y_test, predicted_array_dnn))

Accuracy: 0.8247619047619048


In [ ]:
score,predicted = torch.max(y_pred_val,1)

In [ ]:
score

tensor([ 1.3801, 21.6667,  1.6460,  ...,  5.6688,  4.5472, 25.7727],
       grad_fn=<MaxBackward0>)

In [ ]:
y_test

dtype('int64')

In [ ]:
predicted

tensor([0, 0, 1,  ..., 1, 0, 1])

In [ ]:
y_pred_val.shape

torch.Size([1050, 2])

### Testing with test data

### Use Neural Network Model

In [ ]:
# prepare the data
test_file = '/content/drive/MyDrive/identify_fake_generated_image/test.csv'
df_test = pd.read_csv(test_file)
df_test.head()

id       f_0       f_1       f_2       f_3       f_4       f_5       f_6  \
0   1 -3.388242  0.868285 -0.427619 -0.678964 -1.625735  0.262761  1.243040   
1   2 -0.496920  0.952381  0.989040  0.451422  0.513516 -0.099658 -1.124326   
2   3  1.128369 -0.537951  2.544358  1.165254 -1.904994  0.776961 -0.495768   
3   4  0.051253  1.746814  0.681177  1.844524 -0.327977  1.226839 -0.085519   
4   5  1.423209 -0.983594 -1.694170  1.197507  1.044211  0.518777 -0.298612   

        f_7       f_8  ...    f_1190    f_1191    f_1192    f_1193    f_1194  \
0  1.537751 -0.352028  ... -0.776403 -0.662884 -0.257091 -1.168413  0.223260   
1  0.729430 -0.216224  ...  0.379635 -1.760084  1.125450 -0.328047 -0.880305   
2  0.060111 -1.418468  ...  1.165254 -1.373589 -0.483701 -0.964782 -0.869555   
3  0.379008 -1.003667  ... -0.442288 -2.794472 -0.763468 -0.789832 -0.113209   
4 -0.365174  0.738447  ... -2.624450 -3.200223  0.711422 -0.190394  0.337224   

     f_1195    f_1196    f_1197    f_1198    f_1199  
0 -0.482520 -0.085453 -0.382265 -0.539349 -1.682404  
1 -1.257607  0.964312  2.021104  0.655021 -0.423029  
2  0.066040 -0.444567 -0.531935 -0.878660  1.099488  
3 -2.703150 -2.058728  1.070627 -0.458045 -0.435825  
4 -1.656639  0.707360 -0.562290  1.471181 -0.192000  

[5 rows x 1201 columns]

In [ ]:
# prepare the model and do inference
testmodel = model
testmodel.load_state_dict(torch.load('/content/modelnn.pth'))
testmodel.eval()

Sequential(
  (0): Linear(in_features=1200, out_features=100, bias=True)
  (1): ReLU()
  (2): Linear(in_features=100, out_features=100, bias=True)
  (3): ReLU()
  (4): Linear(in_features=100, out_features=2, bias=True)
)

In [ ]:
test_X = df_test.drop(['id'],axis=1)
# y = df['labels']
test_fix_X = np.float32(test_X)
test_fixest_X= torch.from_numpy(test_fix_X)

In [ ]:
y_pred_test = testmodel(test_fixest_X)

In [ ]:
y_pred_test.shape

torch.Size([2250, 2])

In [ ]:
y_pred_test

tensor([[  1.6749,  -1.5763],
        [ -1.4319,   1.4387],
        [ -1.4814,   1.9281],
        ...,
        [-15.5964,  19.7223],
        [ 36.6098, -38.7542],
        [ -8.7475,  10.4216]], grad_fn=<AddmmBackward0>)